### ISSUE TITLE
LSB init functions are required!

### ISSUE THREAD

**Issue by rajatm0303** [tumblr/collins#269]
I want to install collins in my oracle linux 7 machine.

1. I have downloaded latest zip file of collins i.e. collins-1.3.0.zip.
2. I then executed the setup script under collins/scripts directory. 
        ruby setup
3. After following the installation steps, there appeared a message 

Execute the following commands to finish configuration.
mv /tmp/sysconfig-1424288726-20621 /etc/sysconfig/collins

for dir in /var/log/collins /var/run/collins; do sudo mkdir $dir; sudo chown root $dir; done

sudo -u root /home/labview/Downloads/collins/scripts/collins.sh initdb collins_db_uname collins_db_password

sudo chown -R root /home/labview/Downloads/collins

sudo /home/labview/Downloads/collins/scripts/collins.sh start

curl --basic -u blake:admin:first http://localhost:8080/api/admin/solr

4. When I am executing this command on my oracle linux 
     sudo /home/labview/Downloads/collins/scripts/collins.sh start

it is showing me an error --
LSB init functions are required!
Starting collins... /home/labview/Downloads/collins/scripts/collins.sh: line 149: log_failure_msg: command not found
*** Try checking the logs in /var/log/collins/{stdout,error} to see what the haps are

and then it exits!!

Can u please help me to resolve this issue ??

My machine information is here --

uname -a
Linux labview 3.8.13-55.1.5.el7uek.x86_64 #2 SMP Wed Jan 28 17:08:50 PST 2015 x86_64 x86_64 x86_64 GNU/Linux

Thanks

**Comment by Primer42** [comment]
Hi @rajatm0303 
Can you start by providing the logs that it mentions on the last line? `/var/log/collins/{stdout,error}`
Also, have you tried executing the commands the script tells you to run to finish configuring?
```
Execute the following commands to finish configuration.
mv /tmp/sysconfig-1424288726-20621 /etc/sysconfig/collins
for dir in /var/log/collins /var/run/collins; do sudo mkdir $dir; sudo chown root $dir; done
sudo -u root /home/labview/Downloads/collins/scripts/collins.sh initdb collins_db_uname collins_db_password
sudo chown -R root /home/labview/Downloads/collins
sudo /home/labview/Downloads/collins/scripts/collins.sh start
curl --basic -u blake:admin:first http://localhost:8080/api/admin/solr
```

**Comment by rajatm0303** [comment]
Here are the last logs--

Play server process ID is 20055
Oops, cannot start the server.
To enable GC log rotation, use -Xloggc:<filename> -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=<num_of_files>
where num_of_file > 0
GC log rotation is turned off
Play server process ID is 20273
Oops, cannot start the server.
To enable GC log rotation, use -Xloggc:<filename> -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=<num_of_files>
where num_of_file > 0
GC log rotation is turned off
Play server process ID is 20312
Oops, cannot start the server.
To enable GC log rotation, use -Xloggc:<filename> -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=<num_of_files>
where num_of_file > 0
GC log rotation is turned off
Yes, I was following the steps provided and got stuck in this 5th step as I mentione dabove.

**Comment by Primer42** [comment]
Sorry, the formatting confused me.  I see what you did now.
What version of java are you running with?

**Comment by rajatm0303** [comment]
sorry for the formatting though..
I am suing jre-8u31 version of java. I installed it using the rpm package jre-8u31-linux-x64.rpm

**Comment by Primer42** [comment]
Hmmm so that may be the problem.  We've only ever tested collins using java 6 and 7.  I don't see a reason why it wouldn't work, but I'm betting java 8 expects a different flag to enable GC log rotation.
Do you need to use java 8? Can you try java 7 instead?

**Comment by rajatm0303** [comment]
Yeah, I will try with java 7 and update you then.

**Comment by rajatm0303** [comment]
I tried it with java 7. it is showing up with the same error.

**Comment by rajatm0303** [comment]
So, I found solution for the problem I was facing previously was due to redhat-lsb package not installed on my oracle linux machine.
I did a "yum install redhat-lsb"
now when I did "sudo /home/labview/Downloads/collins/scripts/collins.sh start"

it is giving me a new error--
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
java.lang.IllegalArgumentException: requirement failed: solr.embeddedSolrHome '/Users/bmatheny/Downloads/collins/conf/solr' is not writable or not a directory
        at scala.Predef$.require(Predef.scala:157)
        at collins.solr.SolrConfig$.validateConfig(SolrConfig.scala:35)
        at util.config.Configurable$class.mergeReferenceAndSave(Configurable.scala:106)
        at collins.solr.SolrConfig$.mergeReferenceAndSave(SolrConfig.scala:7)
        at util.config.Configurable$class.initialize(Configurable.scala:43)
        at collins.solr.SolrConfig$.initialize(SolrConfig.scala:7)
        at util.config.Registry$$anonfun$validate$1.apply(Registry.scala:52)
        at util.config.Registry$$anonfun$validate$1.apply(Registry.scala:52)
        at scala.collection.Iterator$class.foreach(Iterator.scala:660)
        at scala.collection.JavaConversions$JIteratorWrapper.foreach(JavaConversions.scala:573)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:73)
        at scala.collection.JavaConversions$JCollectionWrapper.foreach(JavaConversions.scala:592)
        at util.config.Registry$.validate(Registry.scala:52)
        at collins.config.ConfigPlugin.onStart(ConfigPlugin.scala:14)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:84)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:84)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:84)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:84)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:84)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:17)
        at play.api.Play$.start(Play.scala:83)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:51)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:136)
        at play.core.server.NettyServer$$anonfun$main$5.apply(NettyServer.scala:165)
        at play.core.server.NettyServer$$anonfun$main$5.apply(NettyServer.scala:164)
        at scala.Option.map(Option.scala:133)
        at play.core.server.NettyServer$.main(NettyServer.scala:164)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by Primer42** [comment]
```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
```
Are you sure you're running java 7?

**Comment by rajatm0303** [comment]
Yes. I am using java 7. 
I am just guessing that the error is saying about the server machine it need to reach to start collins....

java.lang.IllegalArgumentException: requirement failed: solr.embeddedSolrHome '/Users/bmatheny/Downloads/collins/conf/solr' is not writable or not a directory

**Comment by rajatm0303** [comment]
Yes. I am using java 7.
I am just guessing that the error is saying about the server machine it need to reach to start collins....

java.lang.IllegalArgumentException: requirement failed: solr.embeddedSolrHome '/Users/bmatheny/Downloads/collins/conf/solr' is not writable or not a directory

As you can see "bmatheny" user.

**Comment by rajatm0303** [comment]
This problem got solved by editing the collins_conf_dir configuration in conf/production_starter.conf.

Thanks for the help.

**Comment by Primer42** [comment]
Great glad you were able to figure it out @rajatm0303

**Comment by rajatm0303** [comment]
But I am not able to start using collins. I am figuring out where I am getting wrong. 

I have successfully started collins.sh script. Last step was --
curl --basic -u blake:admin:first http://localhost:8080/api/admin/solr. 

When I run this command it shows be an error: curl: (7) couldn't connect to host. Now when I include a http_proxy for my office netwrok before this command. it doesn't give any error and nothing appears then. 

Can you please tell me how to use collins on my oracle linux 7.

**Comment by rajatm0303** [comment]
I can close this issue and open a new one if you want @Primer42 .

**Comment by Primer42** [comment]
When it started, did it say what port it was running on?  There are two different default conf files floating around, one listens on `8080`, and the other one listens on `9000`.  Try port `9000` and see if that works better.

**Comment by rajatm0303** [comment]
When I ran this command--
sudo /home/labview/Downloads/collins/scripts/collins.sh start                                                                                                                                    
Output was-
Starting collins...                                        [  OK  ]

And initially when I run ruby setup, it said Listen port= 8080

**Comment by Primer42** [comment]
Hmmm OK. That's interesting. 
I'm not sure anything should appear when you use the `api/admin/solr` endopoint.  What happens when you try to visit `localhost:8080` in your browser?

**Comment by rajatm0303** [comment]
it says firefox can't establish a connection to server at localhost:8080 and I tried it with 9000 port also

**Comment by Primer42** [comment]
What did you say before about the http_proxy for your office? Is it possible your network and/or firewall is not allowing you to connect?

**Comment by rajatm0303** [comment]
I have disabled my firewall and I was specifying http_proxy=http://rmdc-proxy.oracle.com before that command to direct traffic through my private network proxy.

**Comment by Primer42** [comment]
This to me smells like a network issue.  Assuming collins is running on your local machine, you should be able to use a browser to access the UI.  Do you need to set up the same proxy on your browser? Can you try to hit other API endpoints, and see if you can get a response from them?

**Comment by rajatm0303** [comment]
So I got to know that my collins server is not running. It is giving an error: Im sorry, but it looks like you may be missing the unlimited strength Java Cryptography Extension. Unfortunately this is required for operations. You can find more details here http://www.bouncycastle.org/wiki/display/JA1/Frequently+Asked+Questions.]

Can you please see over this ??

**Comment by rajatm0303** [comment]
I problem was with Java cryptographic extension for java 7. Now it is working. Thanks for all your support.
