### ISSUE TITLE
API IMPI Intake password validation / error.minLength

### ISSUE THREAD

**Issue by froxart** [tumblr/collins#303]
Hey, i have an issue with the api intake. Exactly adding a ipmi password which is only 5 chars long (default min length = 8). (and yes i know its a bad length, but the IPMI address is not public! And Collins is also able to create random Passwords with a length of 5 chars without any errors)

Example:
```
curl --basic -u blake:admin:first \
-d password=ptest \
http://collins.dev:9000/api/asset/TEST_ASSET/ipmi

{"status":"error","data":{"message":"Data submission error: error.minLength"}}
```

I was able to fix it by editing the **IpmiApi.scala**
FROM:
```
  val IPMI_FORM = Form(
    mapping(
      "username" -> optional(text(1)),
      "password" -> optional(text(8)),
      "address" -> optional(text(7)),
      "gateway" -> optional(text(7)),
      "netmask" -> optional(text(7))
    )(IpmiForm.apply)(IpmiForm.unapply)
  )
```
TO:
```
  val IPMI_FORM = Form(
    mapping(
      "username" -> optional(text(1)),
      "password" -> optional(text(minLength=0, maxLength=16)),
      "address" -> optional(text(7)),
      "gateway" -> optional(text(7)),
      "netmask" -> optional(text(7))
    )(IpmiForm.apply)(IpmiForm.unapply)
  )
```

Is it possible to include it to the collins source. So i doesn't have to maintain and compile my own version for that?

Best Regards,
Kai

**Comment by Primer42** [comment]
I'm not a big fan of 0 length passwords, but I think having a lower limit of 5 and max limit of 16 sounds reasonable to me. Open a pull request, and I can take a look at it.

**Comment by froxart** [comment]
pull request is opend .. hoped its good for you.

Would be really nice to do it. Thanks a lot.
