### ISSUE TITLE
Collins does an LDAP bind twice when logging in from the web

### ISSUE THREAD

**Issue by mattikus** [tumblr/collins#315]
We have an OTP setup with our LDAP authentication but we allow anonymous binds for lookups.

This seems like it should work just fine in Collins with LDAP auth since you allow a base context and only do an authenticated bind when verifying the user's password. However as part of the login flow it appears that the authentication happens twice, based on logs from my ldap server. Since we use an OTP solution, this means the first auth flow succeeds while the second auth fails.

LDAP auth works just fine, however, when doing a basic auth with curl against an API endpoint.

I don't know enough about the Play framework to debug the web authentication flow to figure out why there seem to be two binds to auth a user via the website.

This is verified against the latest master since I need ldaps support for binds.

**Comment by maddalab** [comment]
I created a PR to address the issues

https://github.com/tumblr/collins/pull/316

However, as you are using the latest master, I'll add we have some changes in here that are breaking. If you need any help with those (I don't think you do, since you already have collins running), let me know.

**Comment by mattikus** [comment]
#316 seems to fix my issue completely. :+1:
