### ISSUE TITLE
IPMI Password minLength to 4

### ISSUE THREAD

**Issue by MaximeDevalland** [tumblr/collins#326]
Hi,

can you guys set minLength to 4 OR set minLength to the value in production.conf ( passwordLength )

https://github.com/tumblr/collins/blob/6442ae300ad1009aad04fe2df607fb78471d532d/app/collins/controllers/IpmiApi.scala#L44

Thanks.

**Comment by maddalab** [comment]
sure. want to try making the change?

**Comment by maddalab** [comment]
Thanks Maxime for the PR.
