### ISSUE TITLE
Whitelisting fields to keep on decommission doesn't work

### ISSUE THREAD

**Issue by thenaterhood** [tumblr/collins#363]
Whitelisting attribute fields using keepSomeMetaOnRepurpose doesn't appear to work. Tried with a few combinations of options, with and without deleteMetaOnDecommission which appears to ignore the option and just remove everything (tracing the logic through the code), and without which appears from the code that it should observe the whitelist but instead doesn't remove anything at all.

We're trying to use it in conjunction with deleteIpAddressOnDecommission and deleteIpmiOnDecommision.

Using a blacklist (deleteSomeMetaOnRepurpose) works as expected, which we're considering using in the interim. The relevant section of our configuration, which does not work, is:

    features {
        deleteIpmiOnDecommission = true
        deleteIpAddressOnDecommission = true
        keepSomeMetaOnRepurpose = [COST, INVOICE_NUMBER]
        useWhiteListOnRepurpose = true
    }

Of note, the feature is documented in the config documentation but there is no associated example in the collins configuration examples that we've found. We're using a build of collins from master as of a couple weeks ago.

**Comment by asheepapart** [comment]
It looks like you're using a *capital* "L" in`useWhiteListOnRepurpose`. The code expects `Whitelist`. Did you try with both?

**Comment by maddalab** [comment]
Apologies for the delay @thenaterhood . Thanks @asheepapart.

Nate, did you verify the config you are using. As Benjamin says, the code does expect (useWhitelistOnRepurpose)[https://github.com/tumblr/collins/blob/master/app/collins/util/config/Feature.scala#L44]

**Comment by maddalab** [comment]
Please reopen if issue is unresolved for you.

**Comment by thenaterhood** [comment]
It looks like a lowercase "L" should work fine. I would like to point out that the documentation lists the option with a capital "L" however whenever it is mentioned.

**Comment by Primer42** [comment]
I think the confusion comes from the fact that the configuration is `useWhitelistOnRepurpose`, but the variables in the code are `useWhiteListOnRepurpose`, and the base dev config file has the wrong value too.
I'll go through and fix up the example conf, and fix the docs.

**Comment by Primer42** [comment]
https://github.com/tumblr/collins/pull/365
https://github.com/tumblr/collins/pull/366
