### ISSUE TITLE
Error: Could not retrieve sbt 0.13.5

### ISSUE THREAD

**Issue by kontrafiktion** [tumblr/collins#378]
I wanted to build collins from scratch, but failed at the first step

    ~/src/play-2.0.8/play

results in 

    unresolved dependency: org.scala-sbt#sbt_2.9.1;0.13.5: not found
    Error during sbt execution: Error retrieving required libraries
      (see.../workspaces/me/collins/src/collins/play-2.0.8/framework/sbt/boot/update.log for complete log)
    Error: Could not retrieve sbt 0.13.5

The remote locations that were tried:

    http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt_2.9.1/0.13.5/ivys/ivy.xml
    http://repo1.maven.org/maven2/org/scala-sbt/sbt_2.9.1/0.13.5/sbt_2.9.1-0.13.5.pom

but both URLs return 404

**Comment by maddalab** [comment]
Are you trying to build master or the release tagged version? The documentation is for the release tagged version. Master is much farther along.

On master

Download : https://downloads.typesafe.com/typesafe-activator/1.3.6/typesafe-activator-1.3.6-minimal.zip
Run : ~/Software/play-2.3.9/activator (will vary depending on where you extracted the contents).

**Comment by maddalab** [comment]
Try the documentation on the wiki: https://github.com/tumblr/collins/wiki/Developing-Collins

**Comment by kontrafiktion** [comment]
I tried to build master.
The tagged 1.3.0 works fine, perhaps the readme should state that it is intended for the tagged version and a link to https://github.com/tumblr/collins/wiki/Developing-Collins might help as well. As it is a newbie like me is put off :-(

**Comment by kontrafiktion** [comment]
ah, I didn't use the README but the documentation at http://tumblr.github.io/collins/

**Comment by maddalab** [comment]
We haven't done a historically good job of maintaining documentation. We are working towards improving it and also making the code (design, development) easier by documenting that on the wiki. The  upcoming release (2.0) has some breaking changes and will be released as soon as we have completed the features for the release, these are (a) firehose (b) ipv6 support and (c) retire softlayer custom logic in favor of jclouds.

When we do the release, expect an update on the documentation.

Let me know if you have any questions. I'm hanging out on the collins irc channel and happy to answer any question on there for the next few hours.

**Comment by Primer42** [comment]
To be more exact, we try to keep the documentation in line with the released version, not with the current master.
