### ISSUE TITLE
Ability to delete a specific IP address

### ISSUE THREAD

**Issue by ssgelm** [tumblr/collins#389]
For better or for worse we have a situation where assets somewhat regularly have multiple IP addresses in the same pool.  Ideally we would like a way to delete a single IP from an asset via the API.  Is that reasonable?  If you think it is I am happy to write the code, just making sure that it is functionality you this would be useful.

**Comment by byxorna** [comment]
@ssgelm that would be phenomenal! :+1:
I know I have a handful of use cases that would really benefit from individually management of IPs on an asset, but never got around to implementing. If you would do the leg work, we would gladly accept it!

**Comment by ssgelm** [comment]
Awesome, I'll take a stab at it!

**Comment by ssgelm** [comment]
Well, a year later than I intended but I implemented this in #505.

**Comment by ssgelm** [comment]
This was done in #505.
