### ISSUE TITLE
CLA procedure invalid

### ISSUE THREAD

**Issue by baloo** [tumblr/collins#393]
When submitting CLA to legal@tumblr.com (as said by PDF linked in `CONTRIBUTING.md`), an automated replied is issued:

```
##- Please type your reply above this line -##

Hello and thank you for your message, We no longer accept emails to that =
address. no worries! we have a new form you can fill out to answer you ev=
en better. You can find it at:
https://www.tumblr.com/support
<br>
This message can be copied and pasted into the form, here it is :
<br><br>
----------------------------------------------
```

Maybe you should consider changing the CLA.

The form linked in https://www.tumblr.com/support does not support PDF files.

**Comment by byxorna** [comment]
@baloo sorry about that! We will take care of that. We will figure out what a better email address is to send the CLA to. cc @Primer42

**Comment by Primer42** [comment]
Hi @baloo - sorry for the confusion.  It actually did work, legal@tumbr.com is the correct email address, and I have verified that it was received by our legal team.  We had a misconfiguration that made you receive that response to you email, but that has been fixed now.
So sorry again for the problem, and thanks for your help!
