### ISSUE TITLE
Multiauth documentation is missing

### ISSUE THREAD

**Issue by byxorna** [tumblr/collins#394]
Looks like the docs don't have any details about multiauth. Could be useful dropping some example configs into the documentation

**Comment by defect** [comment]
It's in progress: https://github.com/tumblr/collins/pull/391 :)

I just need to extract some example data for firehose events other than `asset_update` and then it should be good to go.

**Comment by byxorna** [comment]
@defect awesome! Ty!

**Comment by defect** [comment]
Fixed by #391
