### ISSUE TITLE
[doc] Asset Search Result screenshot is not clickable

### ISSUE THREAD

**Issue by rutsky** [tumblr/collins#433]
When I click on `Asset Search Result` screenshot at https://tumblr.github.io/collins/overview.html I'm being redirected to the start of the page, instead of displaying large-scale image.

**Comment by rutsky** [comment]
I'm using Firefox on GNU/Linux.

**Comment by Primer42** [comment]
@rutsky right you are - fix is here:

https://github.com/tumblr/collins/pull/434

Thanks for pointing it out!
