### ISSUE TITLE
question: how to fetch info about a Decommissioned node

### ISSUE THREAD

**Issue by mapuri** [tumblr/collins#436]
Folks,

I would like to get a list of all assets known to Collins (irrespective of their Status) using Collins REST API. However, I am facing some issue when I try to get info for a node that is in `Decommissioned` status.

I am using the asset find API (http://tumblr.github.io/collins/api.html#api-asset-asset-find). And I have tried both with `status=Decommissioned` set in query params and also with not setting any query params for this API. Either way the nodes in `Decommissioned` status don't seem to be returned. Am I missing something or is this expected behavior of the API?

Is there another way to get all assets known to Collins? I would really appreciate any pointers. Please let me know if I can help with providing any other info.

**Comment by Primer42** [comment]
@mapuri I know that I've been able to find for Decommissioned asses before - in fact, I had to generate a list of all our assets in our collins just last week, and got Decomm'd assets.

How many assets are you getting returned, and how many do you expected to be decommissioned?  

What release of collins are you running?

**Comment by mapuri** [comment]
@Primer42 

Thanks for your reply. I am trying this out with Collins [running in a container](https://tumblr.github.io/collins/index.html#quickstart). I just have two nodes in my test environment. For my test I had one asset in `Allocated` state and other node in `Decommissioned` state. And I am noticing that in response to `api/assets` GET query I just get info about one asset in the response. I see the same result on doing a search through Collins UI as well.

I am kind of new to Collins, can you let me know how do I determine it's version in the container environment? From the Collins release page the last release seems to have been out for a while, so I believe that I am running the latest release.

Just to give some more context of my work. I am trying to manage collins using it's REST API for programmatically drive an asset's lifecycle. I have written a very lightweight Go client (https://github.com/contiv/cluster/blob/master/management/src/collins/client.go) for the same. And for a service restart scenario I have a similar use case as you tried where I want to list all assets irrespective of their status.

**Comment by Primer42** [comment]
@mapuri you're in luck - we actually just released a fully functional go client last week!
https://github.com/tumblr/go-collins
Since its new, we haven't updated all the docs to reflect them yet, but hopefully it can help you.

Can you send me specifically what query you are using to that does not return Decommissioned assets?  Are you just hitting `/apt/assets` directly?

I started up the latest container, ran the [poplate.sh script](https://github.com/tumblr/collins/blob/master/scripts/populate.sh) pointed at the container instead of localhost.

````
$ curl --basic -u blake:admin:first -d status="Decommissioned" -d reason="testing dcomm" -X POST http://192.168.99.100:9000/api/asset/tumblrtag300
{"status":"success:ok","data":{"SUCCESS":true}}
$ curl --basic -u blake:admin:first http://192.168.99.100:9000/api/assets
```
I was able to reproduce the problem you saw - I did not realize this, but I guess the find endpoint ignores decommissioned assets unless you explicitly ask for them.

I agree this is annoying - I'm going to try to dig into the code and see if I can understand better why this happens.

**Comment by mapuri** [comment]
@Primer42 

> we actually just released a fully functional go client last week!

this is cool, thanks for the heads up!! I will definitely look into using this instead of maintaining my own client.

> Are you just hitting /apt/assets directly?

yes, this is what I am doing in my current [client code](https://github.com/contiv/cluster/blob/master/management/src/collins/client.go#L132).

> but I guess the find endpoint ignores decommissioned assets unless you explicitly ask for them.
> ...
>  I'm going to try to dig into the code and see if I can understand better why this happens

thanks for your help with this.

Just as a data point, IIRC in my experiments I have tried making a query as `/api/assets?status=Decommissioned` as well and it didn't return any assets too, so I do feel there is something more going on.

**Comment by Primer42** [comment]
@mapuri - In the setup I outlined above, I was able to do `curl --basic -u blake:admin:first http://192.168.99.100:9000/api/assets?status=decommissioned` and it returned the asset that I decommissioned, so yeah, there may also be something different with your set up.

Are you using any custom configs? Can you try following the steps I outlined, and see if you get the same result still?

**Comment by mapuri** [comment]
@Primer42 

> Are you using any custom configs? 

no, just whatever comes with the container

> Can you try following the steps I outlined, and see if you get the same result still?

ok, let me try it again

**Comment by mapuri** [comment]
@Primer42 

Just an update, if I start Collins container afresh and run the commands as you have described then they work for me as well.

But I still see the same issue when I update asset state in Collins using my client implementation, which tells me the issue might be with my code or the way I am invoking collins APIs. I will need to debug it further. I will close this issue for now.

Thanks again for all your help.
