### ISSUE TITLE
getting started basics

### ISSUE THREAD

**Issue by thesrinivas** [tumblr/collins#441]
I have an xml dump (with bios settings) generated by another utility that I'd like to put into collins db. What are the steps to follow? I see the following errors:
1. curl --basic -H "Accept: text/plain" -u blake:admin:first --data-urlencode  "lldp@${LLDP_FILE}"  'CHASSIS_TAG=Testing this' "${URL}/${TAG}"
   "message Error updating asset: lshw parameter not specified"
2.  curl --basic -H "Accept: text/plain" -u blake:admin:first --data-urlencode "lldp@${LLDP_FILE}" --data-urlencode "lshw@${LSHW_FILE}" --data-urlencode 'CHASSIS_TAG=Testing this' "${URL}/${TAG}"
   "message Error updating asset: Expected root class=system node attribute"

Thanks

**Comment by Primer42** [comment]
Hi @thesrinivas 
Sorry I missed this when it first came in.
Do I understand correctly that you did not use LLDP or LSHW to generate this XML? Collins has a very tight coupling on those tools, so it will not work as you are trying to use it if the XML was not generated by LLDP and LSHW.

**Comment by byxorna** [comment]
@thesrinivas LSHW/lldpctl output is required to induct an asset, unfortunately. If you perform some transforms on your custom XML docs to get it into a format that Collins likes (is adherent to LSHW/LLDP format), that would be awesome to hear about!

I'll mark this as closed, as there is nothing for us to do here.
