### ISSUE TITLE
question: Relationship between asset and asset_type

### ISSUE THREAD

**Issue by onimsha** [tumblr/collins#448]
I know that each asset will have its own asset_type, like a server will use SERVER_NODE by default. But is there any relationship between asset like server and data center? For example asset node1 belong to data center aws., in that case is it possible to use collins to manage that relationship?

I read through the documentation, however i'm unable to figure out that relationship.

**Comment by byxorna** [comment]
@onimsha Nope, there is no implicit or explicit hierarchy between assets (and their types). You can create your own relationships by, for example, declaring that `CHASSIS_ASSET` attribute on server_nodes is the asset tag of the `SERVER_CHASSIS` asset the server lives in. However, that relationship is entirely up to you and your tooling. We have typically done things like this (what hypervisor a VM is on, or what chassis a blade is in, what VC a switch is in) with arbitrary fields, and then prettified the UI with a few decorators to linkify them (https://tumblr.github.io/collins/configuration.html#tag decorators)

**Comment by onimsha** [comment]
thanks @byxorna
