### ISSUE TITLE
Populating Collins - How are people doing this? 

### ISSUE THREAD

**Issue by sarlindo** [tumblr/collins#449]
Just wondering what strategies are people using to initially populate collins? Manual entry? Agents collecting facts about existing systems?

**Comment by roymarantz** [comment]
We use a system called genesis <https://github.com/tumblr/genesis> to do
the population of assets, we call it intake, as well as other hardware
setup.  You could also write a small program to process some other input,
say a CSV file, with some information, but we keep track of a lot for each
asset.
Roy

**Comment by sarlindo** [comment]
Thanks, I quickly looked at https://github.com/tumblr/genesis.

I read the install.md, I still don't think this really explains how to actually make use of this in production and how the overall architecture works? Is there any further detailed documentation you can point me to?

**Comment by roymarantz** [comment]
The general-workflow
<https://github.com/tumblr/genesis#general-workflow> should
give an overview on how everything is supposed to work.  The basic idea is
that you boot a genesis image on a server and either manually or (if the
correct boot line parameter is set) automatically run a `target`.  targets
are collections of `task`s which are written in a ruby DSL and preform
small units of work.  There are md files which are supposed to describe all
the pieces.

As the general-workflow and install readme says, you need dhcp and tftp
servers to support the network booting and a file server for the non-tftp
downloaded files.  We also have a system to generate iPXE menus on the fly,
but ours can't be opened sourced and isn't strictly needed.

It is my hope that the various .md files in the repo would be enough to get
you started.  If you have specific questions or can tell me what you find
unclear, I'll try to explain more.
Roy

**Comment by discordianfish** [comment]
Alternative you can also use my https://github.com/discordianfish/collins-pxe, if you're looking for something a) less complex but also b) less maintained ;)

That being said, this can be closed - right?

**Comment by sarlindo** [comment]
Thanks. Yes pls close.

Sent from my BlackBerry - the most secure mobile device - via the Rogers Network
          Original Message

        Show Details

**Comment by defect** [comment]
That looks cool @discordianfish! Maybe we should add a list of links to "collins related" projects in the readme?

Anyway, good discussion! Closing now :)
