### ISSUE TITLE
Add GPU support

### ISSUE THREAD

**Issue by michaeljs1990** [tumblr/collins#536]
We have some machines that utilize GPUs which we handle now with special roles and as time goes on this will likely turn into a mess of tagging nodes with HAS_GPU, GPU=NVIDIA and GPU_NUM=2. I would rather just get this at induction time and never think about it again.

Going to try to dig into this and get a PR posted soon.

**Comment by michaeljs1990** [comment]
#537 is the fist wack at adding upstream support.

**Comment by defect** [comment]
I do believe this is fixed :) Big thanks @jyundt and @michaeljs1990 !
