### ISSUE TITLE
Publish new version of collins_client and collins_shell

### ISSUE THREAD

**Issue by michaeljs1990** [tumblr/collins#540]
Hey!

Can someone who has access to publish new gems update both of these ruby gems so that I can take advantage of the master version of collins?

Thanks!

**Comment by michaeljs1990** [comment]
@roymarantz @defect

**Comment by defect** [comment]
Hey Michael, sorry for the super long delay. The missing versions should now be available. I also rekindled my hatred for jeweler :)
