### ISSUE TITLE
Hot logo

### ISSUE THREAD

**Issue by michaeljs1990** [tumblr/collins#542]
Can we get a super sweet logo for collins? This will improve the user experience for me significantly since i sometimes find it hard to find collins when i have 20 tabs open and it has no favicon.

<img width="55" alt="screen shot 2017-04-26 at 5 17 34 pm" src="https://cloud.githubusercontent.com/assets/2604634/25457429/4805d002-2aa4-11e7-97a6-f0f0b271c2df.png"> 😢 

This is kinda random but I have this logo I had made for another project that I never launched. It's a sweet chihuahua that in no way relates to the name of this project except that I think we can all imagine it's name might be collins.

![version 1 - color](https://cloud.githubusercontent.com/assets/2604634/25457863/b673f16c-2aa5-11e7-8092-53abd954e54d.png)

**Comment by michaeljs1990** [comment]
cc @byxorna @defect @roymarantz

**Comment by gtorre** [comment]
I like it, 👍

**Comment by byxorna** [comment]
@roymarantz @defect @komapa @ssalevan @maddalab what do you think? I like it as well...

How will it look at 16x16 though?

**Comment by michaeljs1990** [comment]
![image](https://cloud.githubusercontent.com/assets/2604634/26253061/07da4592-3c80-11e7-8dab-2d86792296ea.png)

so 16x16 not great i think at the 32x32 level it starts to look like something though.

**Comment by defect** [comment]
I like it! I'm going to try spinning a collins container up with that as a favicon later to see what it looks like in the toolbar, but i'm sure it'll be a lot better than the default chrome or play one :)

We'll also need to check with legal on our side if there are any extra steps for contributions that aren't strictly code. I'll shoot them an email and let you guys know.

**Comment by defect** [comment]
Looks OK at 16x16 to me in the Chrome tabs bar. Not great, but mostly due to me being lazy and not making the white background transparent :)

Do we need 16x16 though? Shouldn't most semi-recent versions of the most common browsers support at least 64x64?

**Comment by byxorna** [comment]
Tbh all favicons look a bit bootleg, so if it doesn't look stellar I'm not too worried. Transparency would be nice though. Should this change include a bit of branding on the navbar and documentation as well?

Also, can you include screenshots of the tab with common browsers?

**Comment by grahamc** [comment]
This looks great. @defect It looks like you used a favicon and didn't also implement the higher resolution options available these days -- it might make the icon look much better: https://davidwalsh.name/retina-favicons

**Comment by defect** [comment]
@grahamc Hehe yeah. I went early 2000s style for a worst-case :) Still looked pretty decent i thought! Especially if we can get some transparency in there.

Once we get legal sign-off I'll ask the frontend folks for advice, unless people here all ready know best practices for favicons.

**Comment by defect** [comment]
Good news! We got the sign-off from legal. Sorry for the super long delay. Unless someone gets to it before me, I'll work on getting a PR out later this week. It's been a while since I did any frontend work though :)

**Comment by defect** [comment]
Merged in #563. Thanks @michaeljs1990!
