### ISSUE TITLE
Need documentation for how to link a VIP with a SERVER_NODE

### ISSUE THREAD

**Issue by JasonRitchie** [tumblr/collins#552]
The [Concepts page](https://tumblr.github.io/collins/concepts.html#addresses) states the following:

> You can create a configuration asset that holds the VIP for a service, then link that asset to others that will actually share the address.

I cannot find instructions or examples showing how to do this.

**Comment by byxorna** [comment]
@JasonRitchie the link is a logical one, not an actual link in collins. Depending on your environment, you could create a `myservice-vip` Configuration Asset that has the frontend IP, and then set a `VIP=myservice-vip` attribute on assets that you want to use this vip. Your automation can then know to lookup the asset in VIP if present when performing any kind of configuration for a backend device. This could be helped in the UI with [tag decorators](https://tumblr.github.io/collins/configuration.html#tag decorators) to make the VIP value a link to the asset. Generally, its an organizational convention to assign semantics to (and respect) different tags. 

I've done something similar to this for a few different companies using Collins, and its worked well. Does that help answer your question?

**Comment by JasonRitchie** [comment]
I understand now. Thank you for the clear and complete response. It looks like a tag decorator will fit my needs.

**Comment by byxorna** [comment]
Ok, cool! Glad to hear. If you find you have a useful pattern  and feel like writing up a quick tutorial to help others, would you mind opening a PR against the `gh-pages` branch to update docs?
