### ISSUE TITLE
Capture BIOS version information in ServerBase

### ISSUE THREAD

**Issue by jyundt** [tumblr/collins#555]
@byxorna Thoughts on updating the ServerBase model to include a string for BIOS version information? Or would a separate BIOS model be more appropriate?  (E.g. capture additional information like BIOS vendor, BIOS version, BIOS date, etc.)

We are working with our DC teams and realized we need this information in collins. I wanted to get your input before we make any changes / submit a PR.

CC @michaeljs1990 @nshalman

**Comment by byxorna** [comment]
@jyundt I think having more info is certainly useful. I can't think of a reason to not have this information collected.

**Comment by jyundt** [comment]
Ok cool, I'll take a stab at this.
