### ISSUE TITLE
method getLshwValues is defined twice

### ISSUE THREAD

**Issue by t1mota** [tumblr/collins#559]
during compile got this error

[error] /root/src/collins/app/collins/models/AssetMeta.scala:220: method getLshwValues is defined twice
[error]   conflicting symbols both originated in file '/root/src/collins/app/collins/models/AssetMeta.scala'
[error]     def getLshwValues(): Set[AssetMeta] = {
[error]         ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 277 s, completed Jun 22, 2017 3:48:15 PM

**Comment by byxorna** [comment]
@t1mota how are you building this? Have you tried a `git clean -xxd`? The build is passing on master branch (see readme) so it must be some oddities with your environment, build tooling, etc.

**Comment by maddalab** [comment]
It is defined twice

https://github.com/tumblr/collins/blob/master/app/collins/models/AssetMeta.scala#L216

**Comment by byxorna** [comment]
@maddalab lovely. somehow travis only is running ruby builds; not scala (`RUN_SCALA=false` for all builds). Doesnt seem like the travis file has changed recently... we need to readd the scala build to the build matrix. https://github.com/tumblr/collins/blame/master/.travis.yml#L33-L40

**Comment by byxorna** [comment]
@t1mota fix committed; wait a bit for the new container to build, and `git`/`docker` `pull` again? Thanks for reporting this!
