### ISSUE TITLE
Split out ruby gems to their own repo(s)

### ISSUE THREAD

**Issue by defect** [tumblr/collins#580]
We should split out the ruby gems from the main collins repo. One reason is that we're currently running the scala unit tests for PRs that are purely ruby changes, and they're notoriously flakey.

Some open questions;

* Should we have a repo per gem? I'm leaning towards yes. Repos are free, right?
* Do we want to deprecate some gems? For instance, we don't really use collins-shell or collins-state at tumblr anymore. I think @matthiasr and @soundcloud is using collins-shell (correct?) but I feel collins-state can probably be deprecated fairly safely.

@roymarantz @qx-xp @gtorre @byxorna

**Comment by matthiasr** [comment]
Yes, we are using collins-shell – it has its quirks but does the trick. I looked into switching to collins-cli but couldn't find some feature I needed immediately (but forgot which one).

I am in favor of separate repos, that also enables installation directly from git for running patches locally. I think in theory that would be possible with multiple gemspec files in the root of the repository, but nit sure how to organize those right.

**Comment by byxorna** [comment]
Yea, I agree @defect. Separate repos sound good
