### ISSUE TITLE
Wrong URL returned for remote assets when querying from CLI with '--remote-lookup'

### ISSUE THREAD

**Issue by nshalman** [tumblr/collins#583]
With the release of [collins-cli-0.2.12](https://rubygems.org/gems/collins-cli/versions/0.2.12) I was very excited to be able to get results from multiple collins servers by querying a single one.

It generally appears to work, so thank you very much to everyone who made that possible!

I did manage to run into an odd corner case:

```
collins find --remote-lookup --link -n <some nodeclass>
```

The resulting URLs all point to the collins instance queried, not accurate URLs to whichever is the actual collins instance where they live.

I mentioned this to @michaeljs1990 and he suggested that this appeared to him to be a problem with data returned from collins itself rather than being an obvious bug in `collins-cli`

**Comment by michaeljs1990** [comment]
Ops sorry that is my bad. This is actually an issue in collins-cli after taking one more look at it.

**Comment by nshalman** [comment]
Thank you for your excellent response time. :)
