### ISSUE TITLE
Inconsistencies in LDAPS document

### ISSUE THREAD

**Issue by lukemgriffith** [tumblr/collins#587]
Under configuration. Authentication states that LDAP over SSL is not supported, yet further down in the configuration options for LDAP there is a Boolean for SSL.

Is it supported or not? And can the documentation be updated to be consistent.

**Comment by defect** [comment]
Sorry for the slow response. Collins does support ldaps, so the part of the docs you're referencing are indeed incorrect. I'll cut a PR to update the docs.

As an aside, I think it still would be wise to run a  LDAP slave on the box next to collins :)  Nothing worse when you have a big outage and you can't reach your inventory management database.

**Comment by defect** [comment]
Closed in #588
