### ISSUE TITLE
Complete the Recipes Section of Docs

### ISSUE THREAD

**Issue by icebourg** [tumblr/collins#68]
We've got a pretty significant deploy of collins going, and it's been a great tool. We've started to get to the point where we really want to start expanding collins via callbacks, and have a tentative idea for what we want to do, but the docs are kind of sparse. The recipes section doesn't have anything listed.

I think the best thing to document first would be the list of replacement variables that are available like the doc for the provision script does. One example &lt;tag&gt;, but are there others? For example, when asset_meta_value_create is called, is there a variable that tells us which value was created?

Without a replacement like that, we'll have to get the logs for that tag and operate anything we find there, but it would be nice to know if we *have* to do that, or if collins will give us the exact values for free if you just know how to ask. :)

I tried looking through the code but I'm not familiar enough with scala to be able to piece out the info I was looking for.

Collins has been a great tool. Thanks for releasing it.

AJ

**Comment by axlroden** [comment]
I have written callbacks, but they don't seem to trigger, let me show you my callback config:
```
callbacks.registry {
  provision {
    on = "asset_update"
    when {
      previous.state = "!Provisioning"
      current.state = "Provisioning"
      current.states = [ ISPROVISIONING ]
    }
    action {
      type = exec
      command = "echo WTF > /opt/wtf.txt"
    }
  }
}
```
Replaced my command with an obvious one :)

And then I try and trigger it with:
```
curl --basic -u apiuser:yes -d status=Provisioning -d reason='test' -d state=ISPROVISIONING http://172.16.1.10:8080/api/asset/00-25-90-68-c7-66
{"status":"success:ok","data":{"SUCCESS":true}}
```
I see no log info on a successful trigger anywhere :\

**Comment by byxorna** [comment]
@axlroden drop the `current.states = [ ...]`. You already are specifying the previous and current state you want to trigger on. This should work:
```
callbacks.registry {
  provisionVlan {
    on = "asset_update"
    when {
      previous.state = "isProvisioning"
      current.state = "isProvisioned"
    }
    action {
      type = exec
      command = "/usr/bin/do_something --tag=<tag> "
    }
  }
}
```

However, I suspect you probably want to use the actual provisioner plugin instead:
```
provisioner {
  enabled=true
  profiles="/etc/collins/profiles.yaml"
  checkCommand = "/usr/local/bin/can_asset_provision --tag=<tag> --opts=tag=<tag>,profile=<profile-id>,suffix=<suffix>,notify=<notify>,noop=true"
  command = "/usr/local/bin/provision_asset_yo --tag=<tag> --opts=tag=<tag>,profile=<profile-id>,suffix=<suffix>,notify=<notify>,set-vlan=PROVISIONING"
}
```

**Comment by axlroden** [comment]
@byxorna thanks, I have tried without my current.states as well without it triggering, but yeah.. provisioner seems a much better fit for what I'm trying at the moment.

I'll try that out.

**Comment by axlroden** [comment]
@byxorna success on provisioner, works great. 

I would really love to get callbacks working for some of my other states though :) is there any way to see debug info on why its not triggering?

**Comment by byxorna** [comment]
@axlroden best way is to just play with it. We have lots of state transitions that trigger all kinds of things. Here are some examples:

```
callbacks.registry {
  runProvisionedCallback {
    on = "asset_update"
    when {
      previous.state = "isProvisioning"
      current.state = "isProvisioned"
    }
    action {
      type = exec
      command = "/usr/bin/do_something_to_newly_provisioned_asset --tag=<tag> "
    }
  }
  provisioningProblem {
    on = "asset_update"
    when {
      previous.state = "!isMaintenance"
      current.state = "isMaintenance"
      current.states = [
        PROVISIONING_PROBLEM
      ]
    }
    action {
      type = exec
      command = "/usr/bin/echo fire a ticket because provisioning failed"
    }
  }

  hardwareProblem {
    on = "asset_update"
    when {
      previous.state = "!isMaintenance"
      current.state = "isMaintenance"
      current.states = [
        IPMI_PROBLEM,
        HARDWARE_PROBLEM,
        HARDWARE_UPGRADE,
        NETWORK_PROBLEM
      ]
    }
    action {
      type = exec
      command = "/usr/bin/echo fire a ticket because the machine needs some help"
    }
  }
```

**Comment by axlroden** [comment]
thanks, and sorry for hijacking this issue.
